#!/bin/bash
echo ‘id’ >> 0-answer.txt
echo ‘No’ >> 2-answer.txt
echo ‘Yes’ >> 3-answer.txt
echo ‘Yes 4-answer.txt
echo ‘No 5-answer.txt
echo ‘True’ 6-answer.txt
echo ‘True’ >> 7-answer.txt
echo ‘True’ >> 8-answer.txt
echo ‘True’ >>  10-answer.txt
echo ‘False’ >> 11-answer.txt
echo ‘True’ >> 12-answer.txt
echo ‘True’ >> 13-answer.txt
echo ‘[1, 2, 3, 4]’ >> 14-answer.txt
echo ‘[1, 2, 3]’ >> 15-answer.tx
echo ‘1’ >> 16-answer.txt
echo ‘’ [1, 2, 3, 4] >> 17-answer.txt
echo ‘[1, 2, 3]’ >> 18-answer.txt
echo ‘def copy_list(l):
    return l.copy()’ >> 
echo ‘’ >> 19-copy_list.py
echo ‘Yes’ >> 20-answer.txt
echo ‘Yes’’ >> Yes’
echo ‘No’ >> 23-answer.txt
echo ‘Yes’ >> 23-answer.txt
